-- INSERT INTO "category" (name) VALUES ( 'may@gmail.com', 'may', 'willem', '123');
-- /*
--     private long id;
--
--     @NotNull
--     @OneToOne()
--     @JoinColumn(name = "user_id")
--     private User user;
--
--     @NotNull
--     private String name;
--
--     @NotNull
--     private String description;
--
-- }
--
-- */
